// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_database/firebase_database.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzhh3I5GZWvT3HxvdOWdmZcqPvkpw50KU',
    appId: '1:40751126425:web:4a966ae42196c2de96e508',
    messagingSenderId: '40751126425',
    projectId: 'project-2bc13',
    authDomain: 'project-2bc13.firebaseapp.com',
    storageBucket: 'project-2bc13.appspot.com',
    measurementId: 'G-N2R883YYTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcyzat3LWUHjBLrXcVqs3Z_GEPvDNMKL0',
    appId: '1:40751126425:android:8675f32bcac8129296e508',
    messagingSenderId: '40751126425',
    projectId: 'project-2bc13',
    storageBucket: 'project-2bc13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa3E6Wzuyey7VkA7b3o5WHr9-Ney4rQA4',
    appId: '1:40751126425:ios:54a909537ac310d896e508',
    messagingSenderId: '40751126425',
    projectId: 'project-2bc13',
    storageBucket: 'project-2bc13.appspot.com',
    iosClientId: '40751126425-4o1re02adf2qjh5mat139a7u1gbl3a2j.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa3E6Wzuyey7VkA7b3o5WHr9-Ney4rQA4',
    appId: '1:40751126425:ios:52673741bd7a8a0d96e508',
    messagingSenderId: '40751126425',
    projectId: 'project-2bc13',
    storageBucket: 'project-2bc13.appspot.com',
    iosClientId: '40751126425-rojoekj7eh2q5se4k9fkn0eor7h1d24d.apps.googleusercontent.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
